/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface CollateralPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MIN_NAT_BALANCE_AFTER_EXIT"
      | "MIN_NAT_TO_ENTER"
      | "MIN_TOKEN_SUPPLY_AFTER_EXIT"
      | "agentVault"
      | "assetManager"
      | "claimAirdropDistribution"
      | "claimFtsoRewards"
      | "debtFreeTokensOf"
      | "debtLockedTokensOf"
      | "delegate"
      | "delegateGovernance"
      | "depositNat"
      | "destroy"
      | "enter"
      | "exit"
      | "exitCollateralRatioBIPS"
      | "fAsset"
      | "fAssetFeeDebtOf"
      | "fAssetFeeDeposited"
      | "fAssetFeesOf"
      | "fAssetRequiredForSelfCloseExit"
      | "optOutOfAirdrop"
      | "payFAssetFeeDebt"
      | "payout"
      | "poolToken"
      | "revokeDelegationAt"
      | "selfCloseExit"
      | "setExitCollateralRatioBIPS"
      | "setPoolToken"
      | "setTopupCollateralRatioBIPS"
      | "setTopupTokenPriceFactorBIPS"
      | "supportsInterface"
      | "token"
      | "topupCollateralRatioBIPS"
      | "topupTokenPriceFactorBIPS"
      | "totalCollateral"
      | "totalFAssetFeeDebt"
      | "totalFAssetFees"
      | "undelegateAll"
      | "undelegateGovernance"
      | "upgradeWNatContract"
      | "virtualFAssetOf"
      | "wNat"
      | "withdrawCollateralWhenFAssetTerminated"
      | "withdrawFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "Entered" | "Exited" | "IncompleteSelfCloseExit"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MIN_NAT_BALANCE_AFTER_EXIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_NAT_TO_ENTER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_TOKEN_SUPPLY_AFTER_EXIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "assetManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimAirdropDistribution",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimFtsoRewards",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "debtFreeTokensOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "debtLockedTokensOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "delegate",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "delegateGovernance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositNat",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "destroy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "enter",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "exit",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "exitCollateralRatioBIPS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "fAsset", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "fAssetFeeDebtOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fAssetFeeDeposited",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fAssetFeesOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fAssetRequiredForSelfCloseExit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "optOutOfAirdrop",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "payFAssetFeeDebt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "payout",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "poolToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "revokeDelegationAt",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "selfCloseExit",
    values: [BigNumberish, boolean, string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setExitCollateralRatioBIPS",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPoolToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTopupCollateralRatioBIPS",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTopupTokenPriceFactorBIPS",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "topupCollateralRatioBIPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "topupTokenPriceFactorBIPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalCollateral",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalFAssetFeeDebt",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalFAssetFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "undelegateAll",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "undelegateGovernance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeWNatContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "virtualFAssetOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "wNat", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawCollateralWhenFAssetTerminated",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFees",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "MIN_NAT_BALANCE_AFTER_EXIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_NAT_TO_ENTER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_TOKEN_SUPPLY_AFTER_EXIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "agentVault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "assetManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimAirdropDistribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimFtsoRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "debtFreeTokensOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "debtLockedTokensOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "delegate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "delegateGovernance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "depositNat", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "destroy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "enter", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "exit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "exitCollateralRatioBIPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fAsset", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fAssetFeeDebtOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fAssetFeeDeposited",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fAssetFeesOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fAssetRequiredForSelfCloseExit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "optOutOfAirdrop",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "payFAssetFeeDebt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "payout", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "poolToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeDelegationAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "selfCloseExit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setExitCollateralRatioBIPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPoolToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTopupCollateralRatioBIPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTopupTokenPriceFactorBIPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "topupCollateralRatioBIPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "topupTokenPriceFactorBIPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalFAssetFeeDebt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalFAssetFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "undelegateAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "undelegateGovernance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeWNatContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "virtualFAssetOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "wNat", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawCollateralWhenFAssetTerminated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFees",
    data: BytesLike
  ): Result;
}

export namespace EnteredEvent {
  export type InputTuple = [
    tokenHolder: AddressLike,
    amountNatWei: BigNumberish,
    receivedTokensWei: BigNumberish,
    addedFAssetFeesUBA: BigNumberish,
    newFAssetFeeDebt: BigNumberish,
    timelockExpiresAt: BigNumberish
  ];
  export type OutputTuple = [
    tokenHolder: string,
    amountNatWei: bigint,
    receivedTokensWei: bigint,
    addedFAssetFeesUBA: bigint,
    newFAssetFeeDebt: bigint,
    timelockExpiresAt: bigint
  ];
  export interface OutputObject {
    tokenHolder: string;
    amountNatWei: bigint;
    receivedTokensWei: bigint;
    addedFAssetFeesUBA: bigint;
    newFAssetFeeDebt: bigint;
    timelockExpiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExitedEvent {
  export type InputTuple = [
    tokenHolder: AddressLike,
    burnedTokensWei: BigNumberish,
    receivedNatWei: BigNumberish,
    receviedFAssetFeesUBA: BigNumberish,
    closedFAssetsUBA: BigNumberish,
    newFAssetFeeDebt: BigNumberish
  ];
  export type OutputTuple = [
    tokenHolder: string,
    burnedTokensWei: bigint,
    receivedNatWei: bigint,
    receviedFAssetFeesUBA: bigint,
    closedFAssetsUBA: bigint,
    newFAssetFeeDebt: bigint
  ];
  export interface OutputObject {
    tokenHolder: string;
    burnedTokensWei: bigint;
    receivedNatWei: bigint;
    receviedFAssetFeesUBA: bigint;
    closedFAssetsUBA: bigint;
    newFAssetFeeDebt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IncompleteSelfCloseExitEvent {
  export type InputTuple = [
    burnedTokensWei: BigNumberish,
    redeemedFAssetUBA: BigNumberish
  ];
  export type OutputTuple = [
    burnedTokensWei: bigint,
    redeemedFAssetUBA: bigint
  ];
  export interface OutputObject {
    burnedTokensWei: bigint;
    redeemedFAssetUBA: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CollateralPool extends BaseContract {
  connect(runner?: ContractRunner | null): CollateralPool;
  waitForDeployment(): Promise<this>;

  interface: CollateralPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MIN_NAT_BALANCE_AFTER_EXIT: TypedContractMethod<[], [bigint], "view">;

  MIN_NAT_TO_ENTER: TypedContractMethod<[], [bigint], "view">;

  MIN_TOKEN_SUPPLY_AFTER_EXIT: TypedContractMethod<[], [bigint], "view">;

  agentVault: TypedContractMethod<[], [string], "view">;

  assetManager: TypedContractMethod<[], [string], "view">;

  claimAirdropDistribution: TypedContractMethod<
    [_distribution: AddressLike, _month: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  claimFtsoRewards: TypedContractMethod<
    [_ftsoRewardManager: AddressLike, _lastRewardEpoch: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  debtFreeTokensOf: TypedContractMethod<
    [_account: AddressLike],
    [bigint],
    "view"
  >;

  debtLockedTokensOf: TypedContractMethod<
    [_account: AddressLike],
    [bigint],
    "view"
  >;

  delegate: TypedContractMethod<
    [_to: AddressLike, _bips: BigNumberish],
    [void],
    "nonpayable"
  >;

  delegateGovernance: TypedContractMethod<
    [_to: AddressLike],
    [void],
    "nonpayable"
  >;

  depositNat: TypedContractMethod<[], [void], "payable">;

  destroy: TypedContractMethod<[_recipient: AddressLike], [void], "nonpayable">;

  enter: TypedContractMethod<
    [_fAssets: BigNumberish, _enterWithFullFAssets: boolean],
    [[bigint, bigint]],
    "payable"
  >;

  exit: TypedContractMethod<
    [_tokenShare: BigNumberish, _exitType: BigNumberish],
    [[bigint, bigint]],
    "nonpayable"
  >;

  exitCollateralRatioBIPS: TypedContractMethod<[], [bigint], "view">;

  fAsset: TypedContractMethod<[], [string], "view">;

  fAssetFeeDebtOf: TypedContractMethod<
    [_account: AddressLike],
    [bigint],
    "view"
  >;

  fAssetFeeDeposited: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  fAssetFeesOf: TypedContractMethod<[_account: AddressLike], [bigint], "view">;

  fAssetRequiredForSelfCloseExit: TypedContractMethod<
    [_tokenAmountWei: BigNumberish],
    [bigint],
    "view"
  >;

  optOutOfAirdrop: TypedContractMethod<
    [_distribution: AddressLike],
    [void],
    "nonpayable"
  >;

  payFAssetFeeDebt: TypedContractMethod<
    [_fAssets: BigNumberish],
    [void],
    "nonpayable"
  >;

  payout: TypedContractMethod<
    [
      _recipient: AddressLike,
      _amount: BigNumberish,
      _agentResponsibilityWei: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  poolToken: TypedContractMethod<[], [string], "view">;

  revokeDelegationAt: TypedContractMethod<
    [_who: AddressLike, _blockNumber: BigNumberish],
    [void],
    "nonpayable"
  >;

  selfCloseExit: TypedContractMethod<
    [
      _tokenShare: BigNumberish,
      _redeemToCollateral: boolean,
      _redeemerUnderlyingAddress: string,
      _executor: AddressLike
    ],
    [void],
    "payable"
  >;

  setExitCollateralRatioBIPS: TypedContractMethod<
    [_exitCollateralRatioBIPS: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPoolToken: TypedContractMethod<
    [_poolToken: AddressLike],
    [void],
    "nonpayable"
  >;

  setTopupCollateralRatioBIPS: TypedContractMethod<
    [_topupCollateralRatioBIPS: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTopupTokenPriceFactorBIPS: TypedContractMethod<
    [_topupTokenPriceFactorBIPS: BigNumberish],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [_interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  token: TypedContractMethod<[], [string], "view">;

  topupCollateralRatioBIPS: TypedContractMethod<[], [bigint], "view">;

  topupTokenPriceFactorBIPS: TypedContractMethod<[], [bigint], "view">;

  totalCollateral: TypedContractMethod<[], [bigint], "view">;

  totalFAssetFeeDebt: TypedContractMethod<[], [bigint], "view">;

  totalFAssetFees: TypedContractMethod<[], [bigint], "view">;

  undelegateAll: TypedContractMethod<[], [void], "nonpayable">;

  undelegateGovernance: TypedContractMethod<[], [void], "nonpayable">;

  upgradeWNatContract: TypedContractMethod<
    [_newWNat: AddressLike],
    [void],
    "nonpayable"
  >;

  virtualFAssetOf: TypedContractMethod<
    [_account: AddressLike],
    [bigint],
    "view"
  >;

  wNat: TypedContractMethod<[], [string], "view">;

  withdrawCollateralWhenFAssetTerminated: TypedContractMethod<
    [],
    [void],
    "nonpayable"
  >;

  withdrawFees: TypedContractMethod<
    [_fAssets: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MIN_NAT_BALANCE_AFTER_EXIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_NAT_TO_ENTER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_TOKEN_SUPPLY_AFTER_EXIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agentVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "assetManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "claimAirdropDistribution"
  ): TypedContractMethod<
    [_distribution: AddressLike, _month: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimFtsoRewards"
  ): TypedContractMethod<
    [_ftsoRewardManager: AddressLike, _lastRewardEpoch: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "debtFreeTokensOf"
  ): TypedContractMethod<[_account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "debtLockedTokensOf"
  ): TypedContractMethod<[_account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "delegate"
  ): TypedContractMethod<
    [_to: AddressLike, _bips: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "delegateGovernance"
  ): TypedContractMethod<[_to: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "depositNat"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "destroy"
  ): TypedContractMethod<[_recipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "enter"
  ): TypedContractMethod<
    [_fAssets: BigNumberish, _enterWithFullFAssets: boolean],
    [[bigint, bigint]],
    "payable"
  >;
  getFunction(
    nameOrSignature: "exit"
  ): TypedContractMethod<
    [_tokenShare: BigNumberish, _exitType: BigNumberish],
    [[bigint, bigint]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "exitCollateralRatioBIPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "fAsset"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "fAssetFeeDebtOf"
  ): TypedContractMethod<[_account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "fAssetFeeDeposited"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "fAssetFeesOf"
  ): TypedContractMethod<[_account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "fAssetRequiredForSelfCloseExit"
  ): TypedContractMethod<[_tokenAmountWei: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "optOutOfAirdrop"
  ): TypedContractMethod<[_distribution: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "payFAssetFeeDebt"
  ): TypedContractMethod<[_fAssets: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "payout"
  ): TypedContractMethod<
    [
      _recipient: AddressLike,
      _amount: BigNumberish,
      _agentResponsibilityWei: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "poolToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "revokeDelegationAt"
  ): TypedContractMethod<
    [_who: AddressLike, _blockNumber: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "selfCloseExit"
  ): TypedContractMethod<
    [
      _tokenShare: BigNumberish,
      _redeemToCollateral: boolean,
      _redeemerUnderlyingAddress: string,
      _executor: AddressLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "setExitCollateralRatioBIPS"
  ): TypedContractMethod<
    [_exitCollateralRatioBIPS: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPoolToken"
  ): TypedContractMethod<[_poolToken: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTopupCollateralRatioBIPS"
  ): TypedContractMethod<
    [_topupCollateralRatioBIPS: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTopupTokenPriceFactorBIPS"
  ): TypedContractMethod<
    [_topupTokenPriceFactorBIPS: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[_interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "topupCollateralRatioBIPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "topupTokenPriceFactorBIPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalCollateral"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalFAssetFeeDebt"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalFAssetFees"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "undelegateAll"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "undelegateGovernance"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeWNatContract"
  ): TypedContractMethod<[_newWNat: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "virtualFAssetOf"
  ): TypedContractMethod<[_account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "wNat"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawCollateralWhenFAssetTerminated"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawFees"
  ): TypedContractMethod<[_fAssets: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "Entered"
  ): TypedContractEvent<
    EnteredEvent.InputTuple,
    EnteredEvent.OutputTuple,
    EnteredEvent.OutputObject
  >;
  getEvent(
    key: "Exited"
  ): TypedContractEvent<
    ExitedEvent.InputTuple,
    ExitedEvent.OutputTuple,
    ExitedEvent.OutputObject
  >;
  getEvent(
    key: "IncompleteSelfCloseExit"
  ): TypedContractEvent<
    IncompleteSelfCloseExitEvent.InputTuple,
    IncompleteSelfCloseExitEvent.OutputTuple,
    IncompleteSelfCloseExitEvent.OutputObject
  >;

  filters: {
    "Entered(address,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      EnteredEvent.InputTuple,
      EnteredEvent.OutputTuple,
      EnteredEvent.OutputObject
    >;
    Entered: TypedContractEvent<
      EnteredEvent.InputTuple,
      EnteredEvent.OutputTuple,
      EnteredEvent.OutputObject
    >;

    "Exited(address,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      ExitedEvent.InputTuple,
      ExitedEvent.OutputTuple,
      ExitedEvent.OutputObject
    >;
    Exited: TypedContractEvent<
      ExitedEvent.InputTuple,
      ExitedEvent.OutputTuple,
      ExitedEvent.OutputObject
    >;

    "IncompleteSelfCloseExit(uint256,uint256)": TypedContractEvent<
      IncompleteSelfCloseExitEvent.InputTuple,
      IncompleteSelfCloseExitEvent.OutputTuple,
      IncompleteSelfCloseExitEvent.OutputObject
    >;
    IncompleteSelfCloseExit: TypedContractEvent<
      IncompleteSelfCloseExitEvent.InputTuple,
      IncompleteSelfCloseExitEvent.OutputTuple,
      IncompleteSelfCloseExitEvent.OutputObject
    >;
  };
}
