/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IAgentPing, IAgentPingInterface } from "../IAgentPing";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "agentVault",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "query",
        type: "uint256",
      },
    ],
    name: "AgentPing",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "agentVault",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "query",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "response",
        type: "string",
      },
    ],
    name: "AgentPingResponse",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_agentVault",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_query",
        type: "uint256",
      },
    ],
    name: "agentPing",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_agentVault",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_query",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "_response",
        type: "string",
      },
    ],
    name: "agentPingResponse",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAgentPing__factory {
  static readonly abi = _abi;
  static createInterface(): IAgentPingInterface {
    return new Interface(_abi) as IAgentPingInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IAgentPing {
    return new Contract(address, _abi, runner) as unknown as IAgentPing;
  }
}
