/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAgentOwnerRegistry,
  IAgentOwnerRegistryInterface,
} from "../IAgentOwnerRegistry";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "managementAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "name",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string",
        name: "description",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string",
        name: "iconUrl",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string",
        name: "termsOfUseUrl",
        type: "string",
      },
    ],
    name: "AgentDataChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "value",
        type: "address",
      },
    ],
    name: "Whitelisted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "value",
        type: "address",
      },
    ],
    name: "WhitelistingRevoked",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "managementAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "prevWorkAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "workAddress",
        type: "address",
      },
    ],
    name: "WorkAddressChanged",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_managementAddress",
        type: "address",
      },
    ],
    name: "getAgentDescription",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_managementAddress",
        type: "address",
      },
    ],
    name: "getAgentIconUrl",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_managementAddress",
        type: "address",
      },
    ],
    name: "getAgentName",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_managementAddress",
        type: "address",
      },
    ],
    name: "getAgentTermsOfUseUrl",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_workAddress",
        type: "address",
      },
    ],
    name: "getManagementAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_managementAddress",
        type: "address",
      },
    ],
    name: "getWorkAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_address",
        type: "address",
      },
    ],
    name: "isWhitelisted",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAgentOwnerRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IAgentOwnerRegistryInterface {
    return new Interface(_abi) as IAgentOwnerRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAgentOwnerRegistry {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IAgentOwnerRegistry;
  }
}
